### PR TITLE
Feature marker

### PR DESCRIPTION
**Pull request by lobinho**
I have some more changes that I found to be useful :)
- Left and right click to add markers and display deltas. Enable with checkbox.
- Add checkbox to disable AutoScale. This allows e.g. adding signals and keeping zoom level unchanged.
- Add checkbox to plot with steps.
- Add checkbox to add grid.
- #68 already included.

Cheers

### CODE REVIEW

**Comment by ebranlard** [comment]
Hi Wolfgang, 

That's a lot of great features!
I mostly have comments for the the marker feature: 
- That's basically what I had in mind for the features  #57 and #58!
- To avoid reducing the font, do you think it could make sense to add the (x,y) coordinates on the plot? That's typically what Matlab does. Also the advantage, is that it would also show when exporting the figure. The text might overlap for points too close, but then the user could zoom. 
- When activating "Marker", somehow the "zoom" level is lost (probably because of a redraw) when AutoScale is on. Is there a way around it? Like automatically deactivating "AutoScale" when the user select "Marker". That would be my approach. It's trying to 'outsmart' the user, and can lead to frustration, but I think it can outweights the frustration of losing the zoom level when wanting to add these markers. 
- Can we call it something else than "Marker"? I'm afraid people would confuse this with "Markers" like squares, triangle for scatter. Maybe "Annotate", or "Mark", or "Measure". 
- A plus would be to find the nearest point on the nearest curve, but we can do that  later....

Would it make sense to force "AutoScale" to be on if only one signal is selected? 

The Grid and StepPlot features make perfect sense. In the future, I'd like to have "advanced esthetics" options (placement of the legend, font size, line styles, markers), to a separate menu or a "tab" in the future. But for "basic esthetics" (like scatter, grid), I think it's convenient to have them easily accessible. 


I think long term, we would have to think about some kind of strategy for the user interface since it might become too crowded for newcomers. In general, I do like that we don't need to click in a bunch of menus, I want it to be a fast debugging/plotting tool. I've created an issue to discuss that #71
 
Thanks again for your great work!

**Comment by lobinho** [comment]
Hi Emmanuel,

thanks for your comments. 

- Sorry for interfering with your existing issues and spoiling with your UI.
- Yes, getting the coordinates to the plot instead of to the panel sounds good. I will do that. What do you think about keeping the delta x/y in the panel? This would be possible with same font size.
- There are still a few issues with redrawing eliminating the markers which is not nice. I will try keeping it and will see how it can be done. If possible I would prefer leaving Autoscale unchanged but if not possible otherwise this seems okay as well.
- Sure, I was also not too happy with "Marker". I think I will start with "Measure". Feel free to change this. But maybe it makes sense to split the actual measurement function from the annotation where you could put text to the plot. I think this was what you had in mind? It can still be split relatively easily I'd say.
- For the "Measure", maybe it would be nice to add a column to the InfoPanel for each signal and evaluate it at the vertical lines that were selected? Yes, extending this to the annotations would also be nice.
- Yes, probably it is for the best keeping Autoscale on with only one signal as otherwise the signal might be not visible on making a new selection.

Sounds great adding and grouping these options somehow. I also like that it's really straight forward :)

**Comment by ebranlard** [comment]
Awesome work! I actually meant that it's great that you tackled two of the features I had in mind as TODOs. 

I think it's perfect with the dx and dy next to the x,y. The zoom seems to work well now. 

Another option to mix the annotate and measure could be to pop a new panel (just like when selecting `PDF` of `FFT`), that should give more space to show the measures, and potentially add options. But the way it is right now is great! 

I think I've noticed a couple of small issues: 

- In "Measure Mode", if you select two points, and then switch to "PDF" for instance, a "list.remove" exception pops up (GUIMeasure line 36)

- If you try the measure mode with the default example file (`weio/weio/tests/example_files/FASTIn_arf_coords.txt`), the measure tool fails to get the right point, probably because there are actually two "y" points for a same "x". These kind of situations are fairly unusual, and might be hard to handle. 

- Can you maybe merge with the latest master so I can merge this pull request? 

Thanks again, that's pretty awesome!

**Comment by ebranlard** [comment]
Great! It seems to work pretty well now! I'll do the merge in a couple of days, just in case you want to add something on it.

**Comment by lobinho** [comment]
Alright, I think it should be all pretty okay now :)

**Comment by ebranlard** [comment]
Yes, in the rest of the code I tend to override options when they don't make sense, to increase usability in most common cases, "outsmarting" the user, hopefully for the best... So feel free to do the same, if you judge it appropriate. 
We could potentially save the state of "AutoScale" before "Measure" is activated, and put this state back once the user deselect "Measure".

**Comment by lobinho** [comment]
Alright, the issue with reattaching measurements is now addressed. Also, when adding measurements, the columns are enabled automatically. I moved the plot matrix below the InfoPanel-button. What do you think?
If you don't find any further issues, I would say this is finished from my side :)

**Comment by ebranlard** [comment]
I gave it a try, and it's pretty awesome, and fairly robust! Hats off! 
I'll merge this in a day or two, just in case!

**Comment by lobinho** [comment]
Great, glad to hear that :)

**Comment by ebranlard** [comment]
Thanks again!

**Pull request merged**
