### PR TITLE
Add time-based up/downsample sampler, add x@Min/x@Max regular and measured

### PR DESCRIPTION
**Pull request by cdrtm**

### CODE REVIEW

**Comment by ebranlard** [comment]
Cool, thanks for doing that!

I wonder if your df_new needs to be a copy of df_old, I think that's what I'm doing in the other methods. (memory expensive, but I think we need a full copy when we "add" a new table). 

I like your pure pandas approach too, it might actually be better, but I wonder how it compares to my multi_interp routine.


If you feel like it (it's totally fine if you don't have time), it would be nice to add a unit test. I realized tests are limited for these tools, so it's actually my fault..
I've recently pushed a test here: 
      https://github.com/ebranlard/pyDatView/blob/master/tests/test_signal.py

(as a side note, I use `python -m unittest discover -v tests` ) to run the tests from the root directory. Somehow I have an issue with "discover" picking up the tests from weio and that fails, so for now, I restrict the tests to whatever is in the "tests" directory . Maybe you know a good way to go around it. 

Thanks again for your contributions!

**Comment by cdrtm** [comment]
Thanks for the response!

`df_old.assign()` will return a new copy without modifying df_old, so in effect df_new is a new copy. I have now changed the code though, and the new code does `df_new = df_old.set_index(time_index, inplace=False)`, which also returns a new copy and leaves df_old intact.

I also added `test_up_down_sample` function in test_signal.py to include in the unit tests. The tests ended up highlighting a bug for upsampling, which I fixed by using the `interpolate()` function on the upsampled Series or DataFrame.

**Comment by ebranlard** [comment]
Thanks for doing all that, I'll keep this open for a couple more days (just in case you find more issues), and merge it!

**Comment by cdrtm** [comment]
Sounds good!

BTW, I was comparing delta-x, which uses multiInterp(), and Pandas resample. It looks like multiInterp() doesn't calculate the mean of multiple samples when resampling at bigger samples, and instead produces the same output as every-n. Is this the expected behavior?

Attaching an example plot to compare the behavior. Blue is original (0.1ms sample length), Green is Pandas downsample to 0.5ms with mean(), Orange is delta-x to 0.5ms.

delta-x_vs_time-downsample

**Comment by ebranlard** [comment]
Oh, interesting. I'm not a signal processing expert, is it commonly accepted that when downsamping you need to take the mean of the values? It's a bit like a moving averaging filter then.   

This is the behavior I would expect from the dx function, using the true datapoint (basecon linear interpolation, in your case its equivalent to every-other n datapoints), not the average. But I can see that this can be a wanted feature or not. We should mention this in the help.

**Comment by cdrtm** [comment]
I think you're right, the pure definition of downsampling does not involve averaging the samples.

Regarding averaged-downsampling vs moving-average: With moving-average, you don't change the sample rate, but each new sample incorporates history from previous ones. With averaged-downsampling, you reduce the sample rate, and each new sample is independent of previous ones. You basically lose more information with averaged-downsampling, but end up with a smoother output. 

(Orange is averaged-downsampling by 5, Green is moving average of 5)
mov-avg_vs_time-downsample

I think it's good to have all these methods available to the user, as long as the behavior is clearly spelled out in the help like you mentioned. I'll try to expand the help message.

**Comment by ebranlard** [comment]
Sounds good, this makes sense, I would think a "centered" moving average would give about the same answer as the average down-sampling method at the points where the data is sampled. Thanks a lot for doing these tests, and adding to the help message.

**Comment by cdrtm** [comment]
Expanded a little on the help message to highlight the averaged downsampling behavior.

BTW, what do you think of changing Min/Max so that instead of displaying the y value only in InfoPanel, display the (x, y) coordinates instead? I think this would make it easier to locate the Min/Max points on the plot.

**Comment by ebranlard** [comment]
Hey, thanks for your inputs. 
I don't have a strong opinion regarding the xmin and xmax locations. I'd like the "basic" min and max columns to remain only for the "y" data if possible. I'm guessing you are talking about the "Meas" one?  I personally find it hard to read if there are two values in a column. Maybe we can add `xMin (Meas)` and `yMin(Meas)` ? or maybe the string can be `x=..,y=...`  so that it's clear what's being outputted in the table. 

If you have time, can you describe/show what's your typical use case where you want to know the min location? It might be easier for me to understand.  

Thanks!!

**Comment by cdrtm** [comment]
I like the idea of separating ymin and xmin into different columns, and the xmin cols can be disabled by default to reduce clutter.The typical use case I have in mind is analyzing electrical current over time, looking for peaks and at what time they occurred.On Jun 5, 2021 5:01 PM, "E. Branlard" ***@***.***> wrote:
Hey, thanks for your inputs.
I don't have a strong opinion regarding the xmin and xmax locations. I'd like the "basic" min and max columns to remain only for the "y" data if possible. I'm guessing you are talking about the "Meas" one?  I personally find it hard to read if there are two values in a column. Maybe we can add xMin (Meas) and yMin(Meas) ? or maybe the string can be x=..,y=...  so that it's clear what's being outputted in the table.
If you have time, can you describe/show what's your typical use case where you want to know the min location? It might be easier for me to understand.
Thanks!!

**Comment by ebranlard** [comment]
I've tried and it seems to work well. I'll keep the pull request open a bit more. 

I'm wondering if a tool would be more suitable for finding the min/max and maybe add them to the plot. But that can be for the future :) I can also see that if you use this feature a lot, you might be tired to have the select these signals (since they are not saved, see #92).  But I guess since you are familiar with the code, you can turn them on by default locally for now..

**Comment by cdrtm** [comment]
Thanks for trying! Yep we can add a tool to plot an n-number of minima/maxima or something like that in the future!

I might keep those cols enabled like you mentioned locally for convenience. I'll also keep pushing bug fixes to this branch if I find anymore related to this feature.

**Pull request merged**
