### PR TITLE
Feature toolbar 2x2

### PR DESCRIPTION
**Pull request by lobinho**
Suggestion for toolbar rearrangements as discussed in #71. What do you think about it?

Maybe it would also make sense to increase the default height of the InfoPanel? If you agree, could you maybe do that? I was not able to find it quickly.

### CODE REVIEW

**Comment by ebranlard** [comment]
thanks for doing that. 
Can you check which version of matplotlib you are using? I've introduced the variable `VERSION` in the toolbox, to handle some changes of behavior between version. I'm using version 2.2.3 at the moment. 

I believe in your version you have more "|". 

For version 2.2.3, the following order can be used (I'm doing it in reverse now to be able to use "absolute indices": 
```python
        if tools == 1:
            self.DeleteToolByPos(8) # save
            self.DeleteToolByPos(7) # |
            self.DeleteToolByPos(6) # subplots
            self.DeleteToolByPos(5) # zoom
            #self.DeleteToolByPos(4) # pan, we keep
            self.DeleteToolByPos(3) # |
            self.DeleteToolByPos(2) # arrow > 
            self.DeleteToolByPos(1) # arrow < 
            #self.DeleteToolByPos(0) # home, we keep
            self.zoom() # NOTE: #22 BREAK cursors #12!
        elif tools == 2:
            self.DeleteToolByPos(8) # save
            self.DeleteToolByPos(7) # |
            #self.DeleteToolByPos(6) # subplots, we keep
            #self.DeleteToolByPos(5) # zoom, we keep
            self.DeleteToolByPos(4) # pan
            self.DeleteToolByPos(3) # |
            self.DeleteToolByPos(2) # arrow > 
            self.DeleteToolByPos(1) # arrow < 
            self.DeleteToolByPos(0) # home
```

can you try to handle both cases? 

Thanks a lot!

**Comment by lobinho** [comment]
Hi, 
I am using version 3.3.2 indeed. Thanks for the hint with reverse order. I figured to delete the tools by their names. This is much more elegant and hopefully more robust to potential changes :)
Does it work for you as well?

Oh, which tools do we want to keep on the bottom? Subplots and save or zoom?

**Comment by ebranlard** [comment]
Brilliant! It works for me. I think Subplot and save at the bottom works well

**Comment by ebranlard** [comment]
I've added a small fix for zoom

**Pull request merged**
