### PR TITLE
Adding subplot matrix in 1Tab_nCols mode.

### PR DESCRIPTION
**Pull request by lobinho**
The image for the buttons was added to avoid clipping the text with the small button size. There might be a better solution.

### CODE REVIEW

**Comment by lobinho** [comment]
Issue #67

**Comment by ebranlard** [comment]
Interesting feature! Thanks for contributing, and congrats for making your way in the code, there is a lot of messy parts in it! 

It takes a bit of time to get used to the feature, but it works well. 

If you have a bit of time to work on it more, here's some thoughts: 

- I'd think it's mostly useful for few signals, like 2-6 max, no? Maybe it's worth deactivating the feature when there is more than 6 signals? 
- I think it could be nice to maybe have a button to toggle (show/hide) the matrix, since it might confuse some users, but that can be done later. 
- If that's easily done, I think left click to go back in the state of the button would be a nice-to-have as well! Again, no rush on that..

Let me know what you think!

**Comment by lobinho** [comment]
Thanks for the reply. Well, and thank you for starting the project :)

- I agree, I think it makes sense to hide the matrix in some cases. What do you think about another checkbox to toggle the matrix (hidden per default)? Yes, for a high number of signals it might requires too much space but if it can be hidden that should be enough maybe without introducing a hard limit?
- In the moment left click on the button moves on to the next state, - to 1, 1 to 2, 2 to -. Sure, I can add a way to go back. Maybe using right click? Or what would you suggest?

**Comment by ebranlard** [comment]
Yes, a checkbox sounds great! If you don't mind doing that, I'll merge the pull request afterwards. 

I was indeed thinking of right click to decrease the state (I mixed my left and right in my previous post..). But that's just a "nice to have", and we can do that later. 

Thanks again!

**Comment by lobinho** [comment]
Alright, just added these changes. Let me know if you like it this way :)

**Comment by ebranlard** [comment]
Thanks a lot for that! It's great! 
The checkbox could also be placed in the "InfoPanel", since that's where the matrix pops up, but it's definitely a plot option, so it also makes sense to have it in the PlotPanel.. Anyway, let's see if in the long term we find ways to improve the GUI (#71)

**Pull request merged**
