### PR TITLE
Added yMeas function to get Meas mean/min/max in Info Panel

### PR DESCRIPTION
**Pull request by cdrtm**

### CODE REVIEW

**Comment by ebranlard** [comment]
Thanks for your contribution! 

For the cases I've tested, `find_closest` returns 2 points (probably because `Single=False`), and therefore poitns_left is a `2x2` array. This leads to an issue on the "where" statements, which should then be replaced by `points_left[0,0]`.  I guess we need to distinguish if the number of points returned is 1 or not (as done in the function  `meas` above.).  Alternatively, we can use Single=True.  I'm not on top of the whole "measure" code which was written by someone else.   Feel free to adjust based on what you think makes sense.

**Comment by cdrtm** [comment]
Thanks for the feedback! I didn't account for cases with multiple points. I changed the code to set single=False per your recommendation, let me know if you can think of any other cases that could break it.

**Comment by cdrtm** [comment]
Made it more complete by adding Meas min/max in addition to mean. Changed title to reflect that.

**Comment by ebranlard** [comment]
Sorry for the delay in merging this!

**Pull request merged**
